version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d/etc/nginx/conf.d
      - static_volume:/home/crudl/static
      - media_volume:/home/crudl/media
    depends_on:
      - gunicorn
  gunicorn:
    build:
      context: .
      args:
        PIP_REQUIREMENTS: "${PIP_REQUIREMENTS}"
      command: bash -c "/home/crudl/crudl_env/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 crudl.wsgi:application"
      depends_on:
        - db
      volumes:
        - static_volume:/home/crudl/static
        - media_volume:/home/crudl/media
      expose:
        - "8000"
      environment:
        DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
        DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
        DATABASE_NAME: "${DATABASE_NAME}"
        DATABASE_USER: "${DATABASE_USER}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        EMAIL_HOST: "${EMAIL_HOST}"
        EMAIL_PORT: "${EMAIL_PORT}"
        EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
        EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  volumes:
    postgres_data:
    static_volume:
    media_volume: