# Generated by Django 4.0.5 on 2022-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViralVideo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('embed_code', models.TextField(blank=True, verbose_name='Youtube embed code')),
                ('anonymous_view', models.PositiveIntegerField(default=0, verbose_name='Anonymous impressions')),
                ('authenticated_view', models.PositiveIntegerField(default=0, verbose_name='Authenticated impressions')),
            ],
            options={
                'verbose_name': 'Viral video',
                'verbose_name_plural': 'Viral videos',
            },
        ),
    ]
