# Generated by Django 4.0.5 on 2022-07-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viral_videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viralvideo',
            old_name='anonymous_view',
            new_name='anonymous_views',
        ),
        migrations.RenameField(
            model_name='viralvideo',
            old_name='authenticated_view',
            new_name='authenticated_views',
        ),
    ]
